name: 'sync repos'
description: 'get pull from upstream master and push to origin master'
inputs:
  source-repo: 
    required: true
  target-repo:
    required: true
runs:
  using: "composite"
  steps:
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout master
            git remote add service ${{ inputs.source-repo }} 
            git fetch service
            git pull service master --allow-unrelated-histories 
            git push origin master
        shell: bash